member:
 notes: 欢迎光临
server:
 port: 8085
 host: 127.0.0.1
#数据库相关配置
spring:
   datasource:
      hikari:
         master:
            driverClassName: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://47.115.34.118:3306/food?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
            username: root
            password: ntVklfM5@VMj2pHd
            idleTimeout: 60000
            connectionTimeout: 60000
            validationTimeout: 3000
            loginTimeout: 5
            maxLifetime: 60000
         slave:
            driverClassName: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://47.115.34.118:3306/food?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
            username: root
            password: ntVklfM5@VMj2pHd
            idleTimeout: 60000
            connectionTimeout: 60000
            validationTimeout: 3000
            loginTimeout: 5
            maxLifetime: 60000
logging:
   level:
      com.chihuo.food: debug
# nacos相关配置
nacos.config.endpoint: acm.aliyun.com
nacos.config.namespace: 7670869b-ae01-4ff5-92fb-5e2d0ca7c14d
# 推荐使用 RAM 用户的 accessKey 和 secretKey
nacos.config.access-key: LTAI4Fw1XzGcpzbKGzcp2NuL
nacos.config.secret-key: EDOQ2tzsPv4dSjrEFORHHlqJuE7nmp
# 文件上传后存放的路径   windows:file:F:/image/     linux:file:///data/image/
file:
  upload:
    resource: /pic/
    path: D:/pic/test/
